// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDldqkkcNLP2qbQ2q9VsJncW_cKqVxnfcs',
    appId: '1:834164306114:web:638208f987ab845dfa0b5b',
    messagingSenderId: '834164306114',
    projectId: 'rechoice-auth',
    authDomain: 'rechoice-auth.firebaseapp.com',
    storageBucket: 'rechoice-auth.firebasestorage.app',
    measurementId: 'G-ZM300SG30H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg_dj9aLcn1udNW0pafRjC-1flr3YjPqk',
    appId: '1:834164306114:android:5f2248f4405d53c9fa0b5b',
    messagingSenderId: '834164306114',
    projectId: 'rechoice-auth',
    storageBucket: 'rechoice-auth.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc2aHr8GOuly2Au1rPny8w7H8Q0wW-Y9U',
    appId: '1:834164306114:ios:9e2f46d55feef272fa0b5b',
    messagingSenderId: '834164306114',
    projectId: 'rechoice-auth',
    storageBucket: 'rechoice-auth.firebasestorage.app',
    iosBundleId: 'com.example.rechoiceApp',
  );
}
